version: "3.8"
services:
    # nginx
    nginx:
        container_name: d_nginx
        image: nginx:alpine
        depends_on:
            - app
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    # php
    app:
        container_name: d_php
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        depends_on:
            - mysql
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app-network

    # mysql
    mysql:
        container_name: d_mysql
        image: mysql:5.7
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        volumes:
            - ./.docker_data/mysql:/var/lib/mysql
        networks:
            - app-network

    # phpmyadmin
    phpmyadmin:
        container_name: d_phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
            - mysql
        ports:
            - 800:80
        environment:
            PMA_HOST: mysql
            PMA_PORT: ${DB_PORT}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
